### PR TITLE
starter code

### PR DESCRIPTION
**Pull request by Youssif4**
https://github.com/googlecodelabs/android-kotlin-notifications/compare/master...start#diff-dae494ac04b749d9437e199f5eaf66e6

https://github.com/googlecodelabs/android-kotlin-notifications/compare/master...start#diff-f954bd4ec86a9ff24d958e7494a23b17

https://github.com/googlecodelabs/android-kotlin-notifications/compare/master...start#diff-e9b603b3d3bddbc750e2a980230a749d

https://github.com/googlecodelabs/android-kotlin-notifications/compare/master...start#diff-e75ccb18a8c972be6ffd8c1cc005175c

https://github.com/googlecodelabs/android-kotlin-notifications/compare/master...start#diff-6b4c9481965558396fff98caf258647b

### CODE REVIEW

**Comment by asnawi46** [comment]
#1

**Comment by asnawi46** [comment]
#1

**Comment by asnawi46** [comment]
#3

**Comment by yenerm** [comment]
Can you explain this pr a bit? It looks like you are trying to merge starter code to master branch but master branch hosts the final code where the starter branch hosts the starter code.

**Comment by asnawi46** [comment]
#1

**Pull request closed without merging**
